<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./filecss/admin.css">
    <title>Document</title>
</head>
<body>
    <div class="main">
     <h1>XU LY DU LIEU</h1>
     <form action="xulynoiden.php" method="post">
     <div class="content" >
        <label for="">Nhap Noi Muon Di</label>
        <input type="text" name="noiden">
        <button type="submit" name="btn-submit1">ADD</button>
     </div>

     </form>
     
    </div>
</body>
</html>